name: mecha
channels:
  - conda-forge
  - https://conda.anaconda.org/openalea3
  - https://conda.anaconda.org/openalea3/label/dev
channel_priority: strict
dependencies:
  - python
  - pip
  - pytest
  - numpy
  - scipy
  - ipykernel
  - networkx
  - lxml
  - geopandas
  - matplotlib # bundles pylab
  - shapely
  - pydantic
  - opencv
  - openalea.mtg
  - openalea.granap
  - pyan3 
  - graphviz 
  - python-graphviz
  - pip:
    - "-e ..[doc]"
